### ISSUE TITLE
Competidores

### ISSUE THREAD

**Issue by maribelrb22** [ISPP-AparkApp/aparkapp-doc#25]
- [x] Investigar tecnologías que usan
- [x] Detallar por qué Parkifast es gratuita pero tienen pensado añadir extras de pago (porque no lo han entendido)

**Comment by alejandropiuryp** [comment]
- Se ha cambiado la tabla de competidores directos renombrando algunos campos y detallando el modelo de negocio de cada competidor
- Se ha añadido la tecnología a alto nivel que emplean los competidores directos
