### ISSUE TITLE
Riesgos de la aplicación

### ISSUE THREAD

**Issue by maribelrb22** [ISPP-AparkApp/aparkapp-doc#28]
Detectar riesgos de nuestra aplicación y dar respuesta para mitigarlos.
Incluir problema de los gorillas

**Comment by maribelrb22** [comment]
¿De dónde habeís sacado la tabla para realizar el análisis? Añadir fuente

**Comment by maribelrb22** [comment]
¿No dijimos de incluir el problema de los gorillas?

**Comment by maribelrb22** [comment]
Sería necesario unificar las celdas de las tablas. Hay ocasiones en las que pone Id: "id" en la misma celda y otras en las que pone probabilidad: "0.7" en celdas separadas.

**Comment by eveyugyug** [comment]
Se han realizado los cambios sugeridos y mejorado ciertos puntos. No se ha considerado como riesgo el problema de los gorrillas, ya que no afecta a los objetivos principales del proyecto.
