### ISSUE TITLE
Planificación de sprints

### ISSUE THREAD

**Issue by maribelrb22** [ISPP-AparkApp/aparkapp-doc#33]
Definir cuándo se van a realizar cada caso de uso.
Tener en cuenta las diapositivas de la ev donde viene qué vamos a hacer en cada sprint

**Comment by maribelrb22** [comment]
Hubiera estado bien realizar una tabla con todo, para que sea algo más visual

**Comment by Javitoox** [comment]
- Creo que para el MVP no es necesario un login de usuarios como tal, con usar la aplicación identificando el coche y ahí mismo poniendo algunos datos personales por si ocurre cualquier cosa, sobra. A lo mejor habéis pensando así el login, pero un login dedicado a usuarios no lo veo necesario. Si enfocamos esto así habría que modificar algunas tareas creo yo.
- No sé muy bien que significa lo del prototipo que explicáis en los tres sprints. Si os referís a lo que es la interfaz, no sé si es adecuado llamarle prototipo, en el primer sprint sí, pero después yo creo que aunque sea MVP, al final de todos los sprints tiene que ser una app usable y acabada con lo básico, y creo que dentro de lo básico es su interfaz, aunque luego tenga mejoras. De hecho he buscado si el MVP es un prototipo y no, el prototipo es algo más previo por así decirlo.
- "Listado de usuarios y vehículos (administrador): FRQ-005" no creo que deba ser una tarea. Django lo da hecho y no tenemos que hacer nada, ya que dijimos que no íbamos a hacer una interfaz aparte para el administrador si no que usábamos lo de Django.

**Comment by Jesusjbs** [comment]
- Yo pensaba en un login de usuarios ya que por ejemplo cuando el usuario cree un anuncio a través de la interfaz de la app cómo se vincularía ese anuncio con él, cómo listar los vehículos que tiene en un select si no tenemos nada que identifique de la sesión. Lo de los campos de datos identificativos en el coche no lo hemos pensado puesto que en los mockups no hay tales campos al registrar uno.
- Ya comentado.
- Ya comentado.

**Comment by Javitoox** [comment]
De acuerdo, sí, veo lo que dices, podríamos incluso usar el login que trae django, más que nada es por no perder tiempo con un sistema de login completo para el mvp.
